package com.acme.big_tools_pos.dto;

import lombok.Data;

/**
 * RentalAgreement Class defines the data generated by the Service Layer. It transfers the result of Service layer's
 * calculations to the Main class.
 */
@Data
public class RentalAgreement {
    private String toolCode;
    private String toolType;
    private String toolBrand;
    private String rentalDays;
    private String checkOutDate;
    private String dueDate;
    private String dailyRentalCharge;
    private String chargeDays;
    private String preDiscountCharge;
    private String discountPercent;
    private String discountAmount;
    private String finalCharge;
    private boolean holidayCharge;
    private boolean weekendCharge;
}
